### ISSUE TITLE
Overwrite Templates for my project

### ISSUE THREAD

**Issue by crydotsnake** [django-crispy-forms/crispy-bootstrap5#105]
Hello 👋🏼 

Thanks for creating this package! ❤️ 

How could I overwrite the crispy-forms templates for my project if I installed it with pip?

Thanks a lot!

**Comment by smithdc1** [comment]
Hey @crydotsnake 

The method of overriding templates for this package is the same as crispy-forms core. Here's the relevant section of the doc's, hope this helps.

https://django-crispy-forms.readthedocs.io/en/latest/layouts.html#overriding-layout-objects-templates
