### ISSUE TITLE
field_class applied two times for field_file

### ISSUE THREAD

**Issue by Alireza-Farahani** [django-crispy-forms/crispy-bootstrap5#108]
in `field.html` if `field_class` property is set, inputs are wrapped in a div with field_css as css attribute:
```html
{% if field_class %}<div class="{{ field_class }}">{% endif %}
    {% if field|is_file %}
        {% include 'bootstrap5/layout/field_file.html' %}
    {% elif field|is_select %}
...
```
and in `field_file.html` all thing are wrapped in a div with css class as `field_css`
```html
<div class="{{ field_class }} mb-2">
...
```
which results in nested divs with duplicate css like this: 
```html
<div class="col-12 col-md-9"> 
    <div class="col-12 col-md-9 mb-2"> 
        <div> <input type="file" name="icon" class="form-control" accept="image/*" id="id_icon"> </div>
    </div>
</div>
```
Unfortunately this ruins the UI and file input becomes shorter than other fields. 

Is this intended? If not, what can I do except overriding field_file.html?

**Comment by smithdc1** [comment]
Are you suggesting that the `field_class` should be removed from the `field_file.html` template? Maybe the whole `<div>` too?
