### ISSUE TITLE
Will crispy-bootstrap5 depend on django-crispy-forms in the future?

### ISSUE THREAD

**Issue by tildebox** [django-crispy-forms/crispy-bootstrap5#109]
In the usage area it says that django-crispy-forms must also be installed. Is it planned in the future that only one app needs to be installed if you want to use crispy-bootstrap5?

Will the crispy-bootstrap5 project still be maintained?

**Comment by smithdc1** [comment]
Hey @tildebox 

Yes, both packages will be required and maintained going forward. 

Crispy-forms has a long standing aim to unpackage the template packs (e.g
 crispy-bootstrap5) from Crispy-forms  core (form helper et al).

Thanks!

**Comment by tildebox** [comment]
Thank you for your reply.

Is crispy-bootstrap5 ready for production?

**Comment by smithdc1** [comment]
> 1) Is crispy-bootstrap5 ready for production?

It's my list to bump the status when I come to add django 4.1 support. I
The package has been around for a while now and seems stable enough. 


> django-crispy-forms has an extensive docs (readthedocs.io).

> 2) Where can I find something like that for crispy-bootstrap5?

This is mainly just a template pack so features are rather limited. The main docs are for the core package. The small number of additional features we'll document in the readme. 

Do you think something else is required?
