### ISSUE TITLE
Extra space added when rendering checkboxes with labels

### ISSUE THREAD

**Issue by antoinehumbert** [django-crispy-forms/crispy-bootstrap5#118]
In field.html template, when rendering a checkbox with form_show_labels, the mb-3 class is present twice ([here](https://github.com/django-crispy-forms/crispy-bootstrap5/blob/main/crispy_bootstrap5/templates/bootstrap5/field.html#L7) and [here](https://github.com/django-crispy-forms/crispy-bootstrap5/blob/main/crispy_bootstrap5/templates/bootstrap5/field.html#L12))

Because of this duplicate mb-3 classes, checkbox fields have more space at the bottom than other fields.

The second mb-3 should be removed for consistent rendering with other fields (the same way the duplicated "row" class was removed in https://github.com/django-crispy-forms/crispy-bootstrap5/pull/83/files#diff-9ffc7ba2df774d7f6f3de63e6d8c32576620d52105dcf1d0683ed5f03bfdd4a6)

[This line](https://github.com/django-crispy-forms/crispy-bootstrap5/blob/main/crispy_bootstrap5/templates/bootstrap5/field.html#L12) should be replaced by
`    <{% if tag %}{{ tag }}{% else %}div{% endif %} id="div_{{ field.auto_id }}" class="{% if field|is_checkbox and form_show_labels %}form-check{% else %}mb-3{% if 'form-horizontal' in form_class %} row{% endif %}{% endif %}{% if wrapper_class %} {{ wrapper_class }}{% endif %}{% if field.css_classes %} {{ field.css_classes }}{% endif %}">
`

**Comment by smithdc1** [comment]
Thanks for the report, would be great if you could turn your suggestion into a pull request. 🙏

**Comment by antoinehumbert** [comment]
Hi @smithdc1 , I just created pull request. Please, let me know if some improvements are expected.

**Comment by smithdc1** [comment]
Fixed in #119
