### ISSUE TITLE
Items and help needed for a new release?

### ISSUE THREAD

**Issue by jmoppel** [django-crispy-forms/crispy-bootstrap5#122]
I wondered about the plans for a new release and what help might be needed to make it happen? There was some talk about beefing up the documentation for the next release, but I'm unsure what needs to be done since I found everything I needed in the docs.

**Comment by smithdc1** [comment]
Hey thanks for the comment and appologies for the slow uptake. 

There's larger work being done on crispy-forms core but I think we can go ahead and get a release of this template pack out now. 

Good to hear you found everything in the docs 👍
