### ISSUE TITLE
Support for `input-group`

### ISSUE THREAD

**Issue by alexandremjacques** [django-crispy-forms/crispy-bootstrap5#129]
Does crispy-bootstrap5 have support for Bootstrap's [Input group](https://getbootstrap.com/docs/5.2/forms/input-group/)?

**Comment by smithdc1** [comment]
Yes!

Usage is the same as with the other bootstrap template packs. See the `AppendedText`, `PrependedText` and `PrependedAppendedText` Layout Objects. https://django-crispy-forms.readthedocs.io/en/latest/layouts.html?highlight=input%20grou#bootstrap-layout-objects
