### ISSUE TITLE
Double file field created

### ISSUE THREAD

**Issue by Eth189hunt** [django-crispy-forms/crispy-bootstrap5#138]
I am not sure where to report this, hopefully this is the right place.

I created a for with FileField and there seems to be a big where it is generating 2 choose file fields.

<img width="941" alt="Screenshot 2023-02-28 at 10 50 11 PM" src="https://user-images.githubusercontent.com/24537657/222057554-80e7f288-8879-4072-96f0-2c6598df1c6a.png">
<img width="584" alt="Screenshot 2023-02-28 at 10 50 35 PM" src="https://user-images.githubusercontent.com/24537657/222057568-382f4b41-cd62-4f0b-aebb-26af56887f99.png">
<img width="318" alt="Screenshot 2023-02-28 at 10 51 09 PM" src="https://user-images.githubusercontent.com/24537657/222057574-15b543a4-c7f3-408b-b6cf-d09a1f56a0af.png">

**Comment by smithdc1** [comment]
Hi @Eth189hunt -- I'm afraid I can't reproduce your issue. If you can show a minimal example project reproducing this issue, I'd gladly investigate.
