### ISSUE TITLE
Floating labels -- Alpha 3

### ISSUE THREAD

**Issue by smithdc1** [django-crispy-forms/crispy-bootstrap5#14]
Alpha 3 adds floating labels -- 
https://v5.getbootstrap.com/docs/5.0/forms/floating-labels/

Think this needs a small template change and then some docs to explain how to add the extra class. 

- Add class via `wrapper_class="form-floating"`

- Can this line be moved up above the label -- that is the `label` and `input` sit along side each other within the same `div`? :thinking: 

https://github.com/django-crispy-forms/crispy-bootstrap5/blob/856b7dbbba91a761a352d4de3fd6e424f8a38175/crispy_bootstrap5/templates/bootstrap5/field.html#L41

**Comment by millerthegorilla** [comment]
The following template works for me to create floating fields:
```
{% load crispy_forms_field %}
<div class="form-floating mb-3 has-validation">
    {% crispy_field field required %}
    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
    <div class="invalid-feedback">
	    {% if field.errors %}
		    {% for error in field.errors %}
		        <span id="error_{{ forloop.counter }}_{{ field.auto_id }}"><strong>{{ error }}</strong></span>
		    {% endfor %}
		{% endif %}
    </div>
</div>
```
here is a screen shot of the custom fields in use.   The template above could do with a little padding added to prevent the text being chopped at the bottom.  [https://ibb.co/2v8d7M3](screenshot)

**Comment by millerthegorilla** [comment]
So, I was using the floating field custom html template above, but when I installed the bootstrap5 template using pip and installed apps, the custom float field template stopped working.  I am guessing that there is a new way to make custom fields?

**Comment by smithdc1** [comment]
The way templates are overridden has not changed with this template pack. The below example seems to work fine for me with this template pack. 

```python
Field('text_input', css_class='form-control-lg', template="test.html")
```

Could you share how you are using custom templates?

**Comment by millerthegorilla** [comment]
As per the instructions, I think.  I have the template above in a file in templates folder, and reference it in a file called fields.py which has the following content:
```
from crispy_forms.layout import Field

class FloatingField(Field):
	template = 'fields/posts_and_comments_floating_field.html'


class FileInput(Field):
	template = 'fields/posts_and_comments_file_input.html'
```

**Comment by millerthegorilla** [comment]
its working fine with the bootstrap4 template pack, but when I installed the bootstrap5 template pack all my form fields were messed up.   However, as I am writing this, it occurs to me that I may have had a cache installed (memcache) and perhaps the old files were being served.
I will try again.

**Comment by millerthegorilla** [comment]
nope.  it doesn't work.
not working : https://ibb.co/0ZQhZdC  with crispy-bootstrap5
working : https://ibb.co/j8Xx9f7 with bootstrap4 template and latest bootstrap5 cdn

**Comment by smithdc1** [comment]
Hi @millerthegorilla 

Finally got some time to look at this :smile: 

I think what you've bumped into here is that in bootstrap4, crispy-forms adds `form-control` in python code based on the template pack. The strategy we've been working on for a while is to try and move all the logic into the templates. So changing the third line in your example to `{% crispy_field field 'class' 'form-control' %}` works for me.

However, we then also need to allow for the failing version...

``` HTML+django
{% load crispy_forms_field %}
<div class="form-floating mb-3 has-validation">
    {% if field.errors %}
        {% crispy_field field 'class' 'form-control is-invalid' %}
    {% else %}
        {% crispy_field field 'class' 'form-control' %}
    {% endif %}
    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
    <div class="invalid-feedback">
	    {% if field.errors %}
		    {% for error in field.errors %}
		        <span id="error_{{ forloop.counter }}_{{ field.auto_id }}"><strong>{{ error }}</strong></span>
		    {% endfor %}
		{% endif %}
    </div>
</div>
```

At this stage, my main question is how are you dealing with the need to have a `placeholder`? I've done it by adding something like the example below, but this seems a bit verbose?

``` python
    text_input = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Search'}),
    )
```

Now we have a working example, I'll go and think about how we can get this into the template pack. :thinking:

**Comment by millerthegorilla** [comment]
to tell you the truth, I haven't used a placeholder in any of my inputs, the floating field label has the field name within it, and that has generally been enough, with either labels set in the form class meta class, or relying on the verbose_name of the field.
As soon as I get a moment, I will test the bootstrap 5 template and the new field.
One thing I would say is that the field template above lacks help_text, which I didn't include in my custom field template.

**Comment by smithdc1** [comment]
Hi @millerthegorilla 

Here's where I am with this. 

- normal fields have `<label>` then `<input>`
- floating fields have `<input>` then `<label>`, they also need the `form-floating` class on the wrapping `<div>`. 

So a design question really, we could get something like this to work but we'd have to check for the class in the variable in the template to move the order about. I think this is possible, but it's getting a bit horrid to include in the template. (Even I'm thinking, this is the wrong way to go here). 

``` python
    form.helper.layout = Layout(
        Field("first_name", wrapper_class="form-floating", placeholder="first_name"),
        Field("last_name", wrapper_class="form-floating", placeholder="first_name"),
    )
```

Thinking out loud we could have a new `Field` object, maybe `FloatingField`? We could then add the wrapping class as a default and I'm guessing we could probably do something with the placeholder as well. So we could end up with something like:

``` python
    form.helper.layout = Layout(
        FloatingField("first_name"),
        FloatingField("last_name"),
    )
```

Think I've answered my own question.
