### ISSUE TITLE
Inputs missing required when using table_inline_formset.html template

### ISSUE THREAD

**Issue by petasis** [django-crispy-forms/crispy-bootstrap5#150]
Hi all,

I have a crispy formset form, which is rendered ok (i.e. <input required> is used on required fields).
However, if I specify as template "bootstrap5/table_inline_formset.html", the form is rendered as a table row, but all <input> are missing the required attribute.

I can submit the form(s) with required fields empty.

**Comment by smithdc1** [comment]
Hi @petasis 

I looked into your issue and can confirm this is standard Django behavior. You'll see the same when rendering a formset without crispy-forms. Crispy-forms isn't doing anything special here. The relevant section from the django docs says:

> form fields of formsets won’t include the required attribute as that validation may be incorrect when adding and deleting forms.

https://docs.djangoproject.com/en/4.2/topics/forms/formsets/#formset-validation
