### ISSUE TITLE
Possible accessibility issue: radiobutton template display input fields before labels

### ISSUE THREAD

**Issue by danlerche** [django-crispy-forms/crispy-bootstrap5#152]
radio_checkbox_select.html template in the layouts folder outputs input field before the label, which is confusing for screen readers.

**Comment by smithdc1** [comment]
I checked with the django accessibility team and they were unsure about inputs being before the label being an issue. 

Could you expand on your concern a little please? What specifically is the screen reader doing that's causing the confusion.

**Comment by danlerche** [comment]
The issue was reported to me by a colleague using a screen reader. They said having the input be described before the label was confusing. It may not be an officially recognized WCAG issue, but more a UX thing. In the meantime I'm trying to create our own template pack Here's the form they had tried: 
https://pentictonlibrary.ca/about-us/accessibility/accessibility-feedback-my-experience/

**Comment by smithdc1** [comment]
Just to check I understand. 


You're saying that "yes" / "no" gets read before "May staff contact you about your feedback? (optional) "?

**Comment by danlerche** [comment]
Yes that is correct. (FYI, I've now overridden and rearranged the template on that form I sent. It took me less time to figure out than I thought it would). https://github.com/danlerche/public-library-wagtailCMS/blob/main/webform/templates/crispy_forms_template/layout/radio_checkbox_select.html

**Comment by smithdc1** [comment]
I think using `<formset>` and `<legend>` is likely the way forward here.
