### ISSUE TITLE
InlineRadios displaying errors in bold

### ISSUE THREAD

**Issue by JoGorska** [django-crispy-forms/crispy-bootstrap5#153]
It seems that there is wrong class to display errors in the inline radios. All errors in bootstrap 5 are displaying as red text, this one displays as red text in bold. 

Issue might be coming from template: crispy_bootstrap5/templates/bootstrap5/layout/radio_checkbox_select.html

line 24 says text-danger, but it should be invalid-feedback instead?

Also I would remove <small> tag, all other errors in the form don't use that.

**Comment by smithdc1** [comment]
Thanks for the report. 

I agree the styles are different but they both look the same to me. Using crispy-test-project I see this. 🤔 

![image](https://github.com/django-crispy-forms/crispy-bootstrap5/assets/39445562/0765bd4a-bf7a-4372-b687-13c442a04282)

>  All errors in bootstrap 5 are displaying as red text, 

This seems to be the difference. The errors template wrap error text in `<strong>` tags. So I expect all errors to be in bold. Refs

https://github.com/django-crispy-forms/crispy-bootstrap5/blob/main/crispy_bootstrap5/templates/bootstrap5/layout/field_errors_block.html#L3

Appreciate your thoughts.
