### ISSUE TITLE
Switch not available

### ISSUE THREAD

**Issue by MosesMachua** [django-crispy-forms/crispy-bootstrap5#166]
I get an error when I try to import Switch

![image](https://github.com/django-crispy-forms/crispy-bootstrap5/assets/19628623/23cf43c5-ae57-4fd0-8a27-650ee0af4f18)

I have upgraded to the newest version 2023.10 but I don't see a **Switch** class.

![Screen Shot 2023-12-09 at 3 48 33 PM](https://github.com/django-crispy-forms/crispy-bootstrap5/assets/19628623/a3d0c14e-6dc1-4c81-b990-666301309045)

The above is a screenshot showing **bootstrap5.py** file in my installed packages. No Switch class present. Am I missing something?

**Comment by knowsuchagency** [comment]
I have the same issue. Could it do with the move to CalVer?

**Comment by knowsuchagency** [comment]
Confirmed it's not included in the latest release. 

I added the following to my `requirements.txt` in the meantime: 

```requirements.txt
git+https://github.com/django-crispy-forms/crispy-bootstrap5.git@main#egg=crispy-bootstrap5
```

**Comment by marc-gist** [comment]
> Confirmed it's not included in the latest release.
> 
> I added the following to my `requirements.txt` in the meantime:
> 
> ```
> git+https://github.com/django-crispy-forms/crispy-bootstrap5.git@main#egg=crispy-bootstrap5
> ```

Note: anyone having an issue using the git, I had to do a `pip uninstall crispy-bootstrap5` then install from git url.

**Comment by FruitfulApproach** [comment]
The switches still don't show up...

**Comment by MosesMachua** [comment]
> The switches still don't show up...

Did you update your requirements.txt? This release solved it for me.
**crispy-bootstrap5==2024.10**
