### ISSUE TITLE
Inorrectly work with django-autocomplete-light

### ISSUE THREAD

**Issue by dt50** [django-crispy-forms/crispy-bootstrap5#172]
# Incorrectly work when rendering select field
### Render without select data
![Render without select data](https://github.com/django-crispy-forms/crispy-bootstrap5/assets/32037208/14777543-4382-4769-bccf-b340212b7688)
### Render with select data
![Render with select data](https://github.com/django-crispy-forms/crispy-bootstrap5/assets/32037208/0745d6ec-d376-4484-b7e0-67af5d8980c9)
### form.py
![form.py](https://github.com/django-crispy-forms/crispy-bootstrap5/assets/32037208/f4f14269-c674-42ef-84f6-b0536bb2fc95)
How to solve this problem?

**Comment by smithdc1** [comment]
I'd recommend using a custom template for this individual field. 

https://django-crispy-forms.readthedocs.io/en/latest/layouts.html#overriding-layout-objects-templates

**Comment by dt50** [comment]
Okay, got you, thank you for your reply
