### ISSUE TITLE
Unnecessary pt-0 class on labels in form-horizontal forms

### ISSUE THREAD

**Issue by philgyford** [django-crispy-forms/crispy-bootstrap5#173]
I noticed that the labels in my `.form-horizontal` form weren't lining up with the text in the fields, but were slightly higher:

![Screenshot 2024-04-14 at 18 52 37](https://github.com/django-crispy-forms/crispy-bootstrap5/assets/66670/cdd22184-ce4d-4d3f-9287-ac8e453d57c8)

It looks like [this line](https://github.com/django-crispy-forms/crispy-bootstrap5/blob/main/crispy_bootstrap5/templates/bootstrap5/field.html#L16C26-L16C27) is adding a `pt-0` class to each label if the form is a `form-horizontal` form. If I remove that then the labels and input field text line up.

The [docs for Horizontal Forms in Bootstrap 5](https://getbootstrap.com/docs/5.3/forms/layout/#horizontal-form) only show a `pt-0` added to the label for the Radio buttons shown below it.

**Comment by marc-gist** [comment]
Interesting, never noticed.  Tried removing, i don't like the placement of the label after removing.  Yes, I agree, its more in-line and 'horizontal' has the form type suggests.  you could simply override the template for horizontal forms.
Would be nice if it was an option like the column sizes are.

**Comment by smithdc1** [comment]
Thanks for the discussion and the input. 🎁

It seems to me that there's not concensus on this. Given the escape hatch of being able to override templates is available I'd suggest that's the best solution here.
