### ISSUE TITLE
Crispy fails finding Django library

### ISSUE THREAD

**Issue by antonyare93** [django-crispy-forms/crispy-bootstrap5#186]
Yesterday, after installing the crispy_bootstrap5 module, and restarting the app, it started crashing with this error message: ModuleNotFoundError: No module named 'crispy_bootstrap5django'
After trying to figure it out, I found out that the crispy_bootstrap module was trying to look up the Django module in the 'crispy_bootstrap5django' folder.
I fixed it by creating a folder named 'crispy_bootstrap5django' with the Django resources the module needs, but it may need a patch.

**Comment by smithdc1** [comment]
Thanks -- this shouldn't be required but it's difficult to diagnose the issue without a small example. Seems like you managed to get it working though so I'll close for now. Happy to re-open if there's a concrete issue that we need to resolve.
