### ISSUE TITLE
field_file.html doesn't call value method

### ISSUE THREAD

**Issue by crimsonhawk47** [django-crispy-forms/crispy-bootstrap5#195]
Looks like everywhere else calls `field.value()` except this file, which just uses value like a property. This causes fields like `ImageField` to render incorrectly. Am I using it wrong or is this an error? 

Looks like changing it to `field.value().url` and `field.value().name` works. 

![image](https://github.com/user-attachments/assets/8a2b365e-318d-4a9a-9fb2-b1616a1d43c6)

**Comment by smithdc1** [comment]
Hi @crimsonhawk47 

> Looks like changing it to field.value().url and field.value().name works.

Accessing methods with `()` like in `field.value().url` doesn't look like valid [django template (DTL) code](https://docs.djangoproject.com/en/5.1/ref/templates/language/#accessing-method-calls) to me. The crispy-form templates are based upon using the DTL. Your example looks to me like it could be Jinja2? 

It seems to work for me when using the [crispy-test-project](https://github.com/django-crispy-forms/crispy-test-project), but I could be looking at it wrong. 

If you could share a minimal reproduction that would be helpful.
