### ISSUE TITLE
Hack to including bootstrap5 template in crispy-forms

### ISSUE THREAD

**Issue by tunecrew** [django-crispy-forms/crispy-bootstrap5#20]
Would love to know if I've missed a better way to do this:

- crispy-forms and crispy-bootstrap5 installed

In order to use the bootstrap5 template, however, I had to so this in my Django's `settings.py` file:

```
CRISPY_ALLOWED_TEMPLATE_PACKS = '../../crispy_bootstrap5/templates/bootstrap5'
CRISPY_TEMPLATE_PACK = '../../crispy_bootstrap5/templates/bootstrap5'
```

If I specify them as just this:

```
CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap5'
CRISPY_TEMPLATE_PACK = 'bootstrap5'
```

I get this:

```
TemplateSyntaxError at /accounting/received_statement
crispy tag's template_pack argument should be in ('bootstrap', 'uni_form', 'bootstrap3', 'bootstrap4')

```

**Comment by smithdc1** [comment]
Wow I'm impressed someone used this so quickly!

Yes this is not right is it. In my local testing I have it in my settings as you suggest. (Really need to update the readme). So I'm not immediately sure what is wrong here.

I'll have a look later to see what happens if I install it in a new project. 

In the meantime and I'm sure you have, but just to check, have you added it to your `installed_apps`?

**Comment by tunecrew** [comment]
Yes `installed_apps` looks like this:

```
INSTALLED_APPS += [
    'crispy_forms',
    'crispy_bootstrap5',
]
```

It seems to me this is just an issue of the path that `crispy_forms` uses when searching for additional templates. Is there a variable to set this path for `crispy_forms`?

**Comment by smithdc1** [comment]
Hmm. I setup a fresh project earlier and it worked just fine. 

What's odd about the error message is that bootstrap5 should have been added to the allowed template list via the settings (which you have added) So why does it think it's not there 🤔?

Are you able to share a minimal working example of this?

**Comment by tunecrew** [comment]
> What's odd about the error message is that bootstrap5 should have been added to the allowed template list via the settings (which you have added) So why does it think it's not there 🤔?

How would `crispy-forms` deduce the path to the bootstrap5 template though, as it's installed in a different directory?

> Are you able to share a minimal working example of this?

I'll see if I can reproduce this in a fresh application.

**Comment by cpina** [comment]
I've just followed to readme for an existing application and it worked fine.

Do you still have the problem?

For the question "how does crispy-forms deduce the path to the bootstrap5 template..." it's done partially here:
https://github.com/django-crispy-forms/django-crispy-forms/blob/master/crispy_forms/layout.py#L10 (concatenating bootstrap5 when needed)

`template` value will have a value like `bootstrap5/layout/div.html`. Then crispy-forms relies on Django to find which package might have this template. I think that this relies on settings.py having something like (including importantly `'APP_DIRS': True`):
```
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'project_core.processors.navbar_background.background',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
```

See that `crispy_bootstrap5` package contains a directory structure like `templates/bootstrap5/field.html`.
