### ISSUE TITLE
Adding an input using a helper generates an unrequired label

### ISSUE THREAD

**Issue by alex-way** [django-crispy-forms/crispy-bootstrap5#41]
```python
# forms.py
class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["job_title"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.label_class = "bg-primary p-2 text-white"
        self.helper.form_method = "post"
        self.helper.form_action = "start"
        self.helper.add_input(
            Submit("submit", "Submit", css_class="btn btn-warning text-white")
        )
```

```html
<!-- html output -->
<div id="div_id_job_title" class="mb-3">
  <label for="id_job_title" class="form-label bg-primary p-2 text-white">Job title</label>
  <div>
    <input type="text" name="job_title" maxlength="128" class="textinput textInput form-control" id="id_job_title">
  </div>
</div>

<div class="mb-3">
  <div class="aab bg-primary p-2 text-white"></div>
  <div class="">
    <input type="submit" name="submit" value="Submit" class="btn btn-primary btn btn-warning text-white" id="submit-id-submit">
  </div>
</div>
```
As you can see, when adding an input/submit button an unrequired label is generated.

I'll try to create a PR if I can find the bug later on today

**Comment by drizztguen77** [comment]
I'm not getting any labels marked as required at all. If I change to Field() type then it marks the fields as required but when I use FloatingField() it doesn't show any fields marked as required. Here is what my form init looks like.

`
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-8 create-label'
        self.helper.field_class = 'col-md-4'
        self.helper.layout = Layout(
            Div(
                Row(
                    Field('company_name')
                ),
       ...
`
