### ISSUE TITLE
Integrate with django-crispy-forms?

### ISSUE THREAD

**Issue by spapas** [django-crispy-forms/crispy-bootstrap5#46]
Hello, why is this a separate package and is not integrated with the django-crispy-forms package ? Is it because bootstrap 5 is still in beta ?

**Comment by carltongibson** [comment]
In general we are looking to remove template pack from the main repo rather than adding them to make development of each component more flexible.

**Comment by spapas** [comment]
Excellent thank you I'll use this package in addition to the main one !
