### ISSUE TITLE
Current Status

### ISSUE THREAD

**Issue by smithdc1** [django-crispy-forms/crispy-bootstrap5#5]
For anyone watching :wave: 

Here's what it currently looks like.

https://kind-torvalds-1993bc.netlify.app/

EDIT : 
Updated post first batch of fixes -- 9th Nov

EDIT2:
Updated for today's fixes -- 17th Nov (File field + field labels)

**Comment by ab623** [comment]
Is it me or is the horizontal form on the page not in the horizontal format.

**Comment by mepto** [comment]
Hi, 
Thank you for this package :)
I'm wondering on what basis a template is no longer in the template pack for bootstrap 5 when it was in template packs for previous bootstrap versions. In that case I'm thinking more particularly about the checkboxselectmultiple.html template. Is it discarded on purpose? 
Thanks for your reply.

**Comment by smithdc1** [comment]
We've been able to simplify the the radio/checkbox template logic by relying on more on Django's internal methods. This means that we've been able to create a single template that renders both radio and multiple check boxes. 

Hope this helps.
