### ISSUE TITLE
Add support for accordion-flush

### ISSUE THREAD

**Issue by JimiRecard** [django-crispy-forms/crispy-bootstrap5#60]
Bootstrap5 introduced "accordion-flush" html class, which basically removes borders and rounding from accordions.

This could be added by creating an AccordionFlush python class at bootstrap.py and an accordion-flush.html layout.

Alternatively, the Accordion python class could be modified in order to accept an optional "accordion-flush" css class on the template, since it's the only difference from a standard accordion. I think this solution might be the more elegant one.

I'll try to work it out and propose a PR

**Comment by smithdc1** [comment]
@JimiRecard thanks for the interest. Looking forward to seeing your proposal.

**Comment by JimiRecard** [comment]
Thanks, glad to help.

I think I have a solution that adresses both accordion-flush and accordion always open (see https://getbootstrap.com/docs/5.0/components/accordion/#always-open)
The current behavior is actually to be always open, but I believe that should not be the default, and I don't think there's an option for the single-panel-open behavior

My solution involves changing bootstrap.py, which is a file on the main repository. Think we can manage that? I'll try to make a PR for the files on this repository soon

**Comment by JimiRecard** [comment]
The use case I propose would be as follow:
`self.helper.layout = Layout(
            Accordion(
                AccordionGroup("First", always_open=True),
                AccordionGroup("Second", always_open=True),
                flush=True
            )`

I would need to add the kwargs always_open to the Container class and flush to the Accordion class for that to work

**Comment by JimiRecard** [comment]
I made 2 PRs. Sorry about that, I struggle a lot with git and github.

Let me know what you think. I tested manually a few use cases and it seems to work fine, with the necessary changes do bootstrap.py. I'll see if I can propose the changes to the main repository as well.

Also, I believe bootstrap.py is on the main repository for legacy reasons, right? Maybe the best aproach would be for that file to be on the relevant template packs? Just a curiosity, I'm pretty new to this. Thanks for the help

**Comment by smithdc1** [comment]
I think if we need to make changes to bootstrap.py we should do that in this repo. We're trying to keep new template packs separate from core with a longer term aim of splitting out the existing template packs.

We should be able to inherit from class from core here and make any adjustments we need to here? (I can't quite remember off hand how complex those classes are!)

**Comment by JimiRecard** [comment]
It's as I suspected, then. Thanks

Yeah, I believe we can inherit on the already existing bootstrap5.py file. I don't fully understand the classes but the changes I'm proposing are simple enough (famous last words). I'll test locally and then propose another PR for that
