### ISSUE TITLE
Fix checkbox in table_inline_formset

### ISSUE THREAD

**Issue by JimiRecard** [django-crispy-forms/crispy-bootstrap5#73]
Checkboxes are not rendering correctly in formsets using the table_inline_formset.html template.

Current behavior:
![image](https://user-images.githubusercontent.com/58371938/125990593-0cba5969-e99a-458b-ba60-6e8e62f68525.png)

Expected behavior:
![image](https://user-images.githubusercontent.com/58371938/125990765-0e60ffa3-f739-44ee-aca3-dd851c1ffe87.png)

Note that some checkboxes are actually checked on the first image. The issue seems to be on the field.html template. Will investigate this further and possibly propose a PR

**Comment by smithdc1** [comment]
Thanks for the detailed report. 👍

Did you test this on the main branch. I thought we had fixed this, but I need to get another release out with the fix?

**Comment by JimiRecard** [comment]
It's possible. This was tested with the latest release available through pip, 4.0

**Comment by JimiRecard** [comment]
I'm checking the closed PRs, and I believe you fixed it indeed 😅.
I'll close the issue
