### ISSUE TITLE
Help text template needs minor changes

### ISSUE THREAD

**Issue by SFr682k** [django-crispy-forms/crispy-bootstrap5#80]
Template [layout/help_text.html](https://github.com/django-crispy-forms/crispy-bootstrap5/blob/ade42e934347eb7d89226f8a9cc29faa69602e7d/crispy_bootstrap5/templates/bootstrap5/layout/help_text.html):
```django
{% if field.help_text %}
    {% if help_text_inline %}
        <span id="hint_{{ field.auto_id }}" class="text-muted">{{ field.help_text }}</span>
    {% else %}
        <small id="hint_{{ field.auto_id }}" class="form-text text-muted">{{ field.help_text }}</small>
    {% endif %}
{% endif %}
```

With Bootstrap 5, [`.form-text` no longer sets the `display` property](https://getbootstrap.com/docs/5.1/migration/#forms); therefore both help labels should use `.form-text`, but different tags (`span` for inline, `div` for block) or `.d-*` modifier classes.

Furthermore, `.form-text` applies `$form-text-color`, which defaults to `$text-muted`; therefore, `.text-muted` may be omitted.

**Comment by smithdc1** [comment]
Hi @SFr682k thanks for the report. 

I'm still working through this but I wonder if the change is more than just the class/tags? The example of in-line help text also wraps each item in a `div` with `col-auto`. In Bootstrap4 they used to be siblings of each other? 🤔 

Do you have any views on this?

https://getbootstrap.com/docs/5.1/forms/overview/#form-text
https://getbootstrap.com/docs/4.6/components/forms/#help-text
