### ISSUE TITLE
Cache issue ?

### ISSUE THREAD

**Issue by yesyves** [django-crispy-forms/crispy-bootstrap5#85]
Hi

I just upgraded my app from crispy-bootstrap4 to crispy-bootstrap5 and I am encountering caching issues, where users need to clear their cache (i.e. Shift-CTRL-R, once) in order for the pages to load properly following the update. I was very surprised because I do cache busting for all of my css/js libraries, mostly through offline compression with Django-compress but also through library versioning where the versions number is included in the library's URL. 

So my question is : does crispy-bootstrap5 have its own cache layer ? If so, is it different from crispy-bootstrap4 ?

Thanks for any help !

**Comment by smithdc1** [comment]
Hey,

Slightly out of my depth here but as far as I'm aware crispy forms isn't doing any caching and the only real difference between bs4 and bs5 template packs are the templates. 

Sorry I can't be of more help.

**Comment by yesyves** [comment]
Yeah, the problem is usually (99,9%) on my side.

Thanks for the tips !
