### ISSUE TITLE
form-horizontal

### ISSUE THREAD

**Issue by smithdc1** [django-crispy-forms/crispy-bootstrap5#86]
form-horizontal logic is still in the templates but that doesn't appear to be the right thing to do in bs5?

**Comment by wahajmurtaza** [comment]
need to add '.row' besides '.form-group' , but isn't handled in the library. still figuring how to add it through the helper.
Have you find the solution?

**Comment by inducer** [comment]
Appears to work mostly OK for me. Horizontal forms are still a thing: https://getbootstrap.com/docs/5.1/forms/layout/#horizontal-form

**Comment by StevenMapes** [comment]
I've also notice the HTML generate for horizontal forms does not seem to use the templates generated by BS5 which results in the form labels rendering on one row and the input rendering on the next due to the input not being encapsulated by another div with the additional column class

**Comment by andybarilla** [comment]
I can confirm this is still an issue. The generated code should be:

`<div class="row mb-3">
    <label for="inputEmail3" class="col-sm-2 col-form-label">Email</label>
    <div class="col-sm-10">
      <input type="email" class="form-control" id="inputEmail3">
    </div>
  </div>`

But crispy forms is generating (code manually tweaked to remove htmx and required field stuff):

`<div id="div_id_email" class="mb-3 row">
    <label for="id_email" class="col-form-label">Email</label>
    <input type="color" name="email" class="form-control-color textinput form-control"  id="id_email">
</div>`

**Comment by andybarilla** [comment]
Strike my previous comment. While digging into the code to work on a fix, I saw that it just takes some additional parameters to get things to render correctly. If you include the `field_class` property, crispy renders the additional div:

```python
self.helper.label_class = "col" # or col-lg-2, etc
self.helper.field_class = "col" # or col-lg-8, etc
self.helper.form_class = "form-horizontal"
```

**Comment by smithdc1** [comment]
@andybarilla, thanks for commenting on this with your findings.

On that basis, I'll close this issue. Happy to look at it again if someone has a specific example to work through.
