### ISSUE TITLE
Add support for Switches

### ISSUE THREAD

**Issue by jensenbox** [django-crispy-forms/crispy-bootstrap5#90]
I think it would awesome to incorporate the new Switches as a field type. Ideally it could have a means to override all checkboxes in one go.

https://getbootstrap.com/docs/5.1/forms/checks-radios/#switches

**Comment by smithdc1** [comment]
Sounds reasonable to me. PRs welcome!

**Comment by smithdc1** [comment]
I'm not sure overriding all checkboxes is a good idea. 

For example:

![image](https://github.com/django-crispy-forms/crispy-bootstrap5/assets/39445562/a5f5f48b-9bf6-4876-b35c-018861c197c6)

I think switches should only be a replacement for a single checkbox. A small layout object would seem to be the way to solve this.
