### ISSUE TITLE
Help text not rendering as "safe"

### ISSUE THREAD

**Issue by Archmonger** [django-crispy-forms/crispy-bootstrap5#92]
The bootstrap4 template within crispy forms allows embedded HTML within help text. This simplifies bolding texts and whatnot. `crispy-bootstrap5` does not appear to follow the same convention.

Issue example
![image](https://user-images.githubusercontent.com/16909269/148701922-de76a524-043f-4bd9-b761-2fd68179085f.png)

**Comment by Archmonger** [comment]
I'm seeing this commit in the logs https://github.com/django-crispy-forms/crispy-bootstrap5/commit/52156bf8e3cdb0a89a9292b4cc94ef87ce769e5e that appears to mean that the removal of safe was intentional.

I personally don't see much of a problem with help_text being safe, as help_text is typed by the developer. If they want to inject HTML inline via a string, I'd say just let them.

I don't think the scenario exists where help text can unintentionally bork a page.

**Comment by smithdc1** [comment]
Yes, we should restore the safe filter on help text to be consistent with Django itself. See. 

https://github.com/django/django/commit/4c60c3edff4312303e1021fca47ed52c2152d285
