### ISSUE TITLE
Bootstrap 5 set selected option value

### ISSUE THREAD

**Issue by shawnngtq** [django-crispy-forms/crispy-bootstrap5#96]
* Package version: 1.14.0
* Django version: 4.0.2
* Python version: 3.10.2
* Template pack: (Optional) crispy-bootstrap5==0.6

### Description:

I think by default, bootstrap `selected` option doesn't have `value` attribute. Is there anyway we can add it via this?

Or I have to create JavaScript function to add that?

### Preferably also include:

- [ x ] Example Django Crispy Forms code
- [  ] Screenshots
- [ x ] Actual HTML generated
- [ x ] Expected HTML

Django code
```python
class RandomChoices(models.TextChoices):
    DEFAULT = "", _("---")
    A = "A", _("A")
    B = "B", _("B")


class RandomForm(forms.Form):
    random = forms.ChoiceField(
        choices=RandomChoices.choices,
        required=False,
    )
```

Template
```html
<div class="mb-3">
    <h3 class="h6 mb-2">Random choice</h3>
    {{ random|add_class:"form-select form-select-sm mb-2" }}
</div>
```

Generated HTML
```html
<select class="form-select form-select-sm mb-2" id="id_random" name="random">
    <option selected="">---</option>
    <option value="A">A</option>
    <option value="B">B</option>
</select>
```

Expected HTML
```html
<select class="form-select form-select-sm mb-2" id="id_random" name="random">
    <option value="" selected>---</option>
    <option value="A">A</option>
    <option value="B">B</option>
</select>
```

**Comment by smithdc1** [comment]
Hi @shawnngtq 👋 

Your template looks like `django-widget-tweaks` style rather than `crispy-forms`. 

If you were using the crispy-filter (say) I'd have expected in the template to see `{{ random|crispy }}` rather than `{{ random|add_class...}}`. 🤔 

Amending the existing [test](https://github.com/django-crispy-forms/crispy-bootstrap5/blob/main/tests/results/test_select.html) to have to have a default option like your form I get:

``` html
<form method="post">
  <div class="mb-3" id="div_id_select_input">
    <label class="form-label" for="id_select_input">Select input</label>
      <select class="form-select select" id="id_select_input" name="select_input">
        <option value="1">Option one</option>
        <option value="2">Option two</option>
        <option value="3">Option three</option>
        <option selected value="">Option 4</option>
      </select>
  </div>
</form>
```

**Comment by shawnngtq** [comment]
Hi @smithdc1

Yes, you are right, I am using both this and `django-widget-tweaks`, and I kinda mix them up. So this is considered off-topic, sorry about that.

I am going to try the `crispy` way to see if I can get expected output. Will update here again.

**Comment by smithdc1** [comment]
https://github.com/django-crispy-forms/crispy-bootstrap5/commit/eccd51491d6bfa9399349901247614ba44aed27e

Here's the example I mocked up. Tests's don't pass on everything as I broke unrelated tests with this change. Shows the scenario you ave though with the html being generated as per above.

**Comment by smithdc1** [comment]
Ahh. You are using `TextChoices` where as I used tuples. 

What happens if you render your form with "just" Django?

**Comment by shawnngtq** [comment]
I tried with list of tuples and tuple of tuples for the `choices`

```python
random = forms.ChoiceField(
    # choices=RandomChoices.choices,
    choices=[("", _("---")), ("A", _("A")), ("B", _("B"))],
    required=False,
)

random = forms.ChoiceField(
    # choices=RandomChoices.choices,
    choices=(("", _("---")), ("A", _("A")), ("B", _("B"))),
    required=False,
)
```

The output is same as when I use `TextChoices`. I am quite sure it's not the reason.

```html
<select class="select form-select" id="id_random" name="random">
  <option selected="">---</option>
  <option value="A">A</option>
  <option value="B">B</option>
</select>
```

I noticed that the empty string value is what matters. When I replace "" or `None` with something else, the `selected` attribute will be replaced by `value`.

```python
class RandomChoices(models.TextChoices):
    DEFAULT = "Default", _("---")
    A = "A", _("A")
    B = "B", _("B")

random = forms.ChoiceField(
    choices=RandomChoices.choices,
    required=False,
)
```

```html
<select class="select form-select" id="id_random" name="random">
  <option value="Default">---</option>
  <option value="A">A</option>
  <option value="B">B</option>
</select>
```

The thing is that django `CharField` prefer "" over `None`, that's why I kept it "" for DEFAULT

**Comment by shawnngtq** [comment]
Here are some tests I did.

Vanilla django, it works fine: https://forum.djangoproject.com/t/django-choicefield-empty-string-value/12458/3

What is interesting here is that so long I add `crispy_forms` and `crispy_bootstrap5` under `INSTALLED_APPS`, even if I don't use any crispy method (not even `{% load crispy_forms_tags %}`), it cause the `selected=""`

**Comment by shawnngtq** [comment]
I found out the reason, it's not due to this library, but due to https://github.com/adamchainz/django-minify-html.
